#!/bin/bash

# Creates a day's directory with ts file and attempts to download the input

if [ -z "$1" ]; then
  echo "Usage: scripts/create <day>"
  exit 1
fi

DAY=$(printf "%02d" "$1")
DIR="day${DAY}"

# Creates the directory if it doesnt already exist
if [ -d "$DIR" ]; then 
  echo "Directory already exists blud 💀"
else 
  echo "Creating directory 🤓..."
  mkdir "$DIR"
fi

# Downloads the input, putting it into the correct file
bash ./scripts/download "$1"

# Creates the test file if it doesn't exist
if [ ! -f "$DIR/test.txt" ]; then 
  echo "Creating Test File..."
  touch "$DIR/test.txt"
fi

# Creates input file with starter code if its not there
DEFAULT_CODE="import getInput from \"../utils/getInput\"\n\nconst input = getInput($1).split(\"\\\n\");\n\n\n\n\n\nconsole.log(0);"
if [ -f "$DIR/part1.ts" ]; then
  echo "Part 1 codes already in the house my man"
else 
  echo "Creating part 1 code file..."
  touch "$DIR/part1.ts"
  echo "Filling code file..."
  printf "$DEFAULT_CODE" > "$DIR/part1.ts"
fi

if [ -f "$DIR/part2.ts" ]; then
  echo "Part 2 codes already in the house my man"
else 
  echo "Creating part 2 code file..."
  touch "$DIR/part2.ts"
  echo "Filling code file..."
  printf "$DEFAULT_CODE" > "$DIR/part2.ts"
fi

echo "All good sigma ✊. Time to grind ✅💰💵"