#!/bin/bash

# Creates a day's directory with ts file and attempts to download the input

if [ -z "$1" ]; then
  echo "Usage: scripts/create <day>"
  exit 1
fi

DAY=$(printf "%02d" "$1")
DIR="day${DAY}"

# Creates the directory if it doesnt already exist
if [ -d "$DIR" ]; then 
  echo "Directory already exists blud 💀"
else 
  echo "Creating directory 🤓..."
  mkdir "$DIR"
fi

# Downloads the input, putting it into the correct file
bash ./scripts/download "$1"

# Creates input file with starter code if its not there
if [ -f "$DIR/index.ts" ]; then
  echo "Codes already in the house my man"
else 
  echo "Creating code file..."
  touch "$DIR/index.ts"
  echo "Filling code file..."
  echo -e "import getInput from \"../utils/getInput\"\n\nconst input = getInput($1);" > "$DIR/index.ts"
fi

echo "All good sigma. Time to grind ✅💰💵"